### ISSUE TITLE
The unfollow feature does not work

### ISSUE THREAD

**Issue by david-kariuki** [Correia-jpv/github-follow-bot#8] opened 2022-08-08 20:35 UTC
**Describe the bug**
The unfollow feature does not work. It fails with the message, **nothing to unfollow!**

**Comment by david-kariuki** [comment] 2022-09-04 14:07
Hello, is there a scheduled fix for this?

**Comment by david-kariuki** [comment] 2022-09-04 20:15
I fixed the issue.

I changed this line `parser.add_argument('-mu', '--max-unfollow', help="Max Number of People to Unfollow")` to 
parser.add_argument('-mu', '--max', help="Max Number of People to Unfollow")

and mnof = `args.max_followers` to `mnof = args.max`

The argument `max_followers` had not been defined in the parser. Also, I changed `max-unfollow` to `max since the special character `-` was breaking that line.

**Comment by Correia-jpv** [comment] 2022-09-09 16:01
> I fixed the issue.
> 
> I changed this line `parser.add_argument('-mu', '--max-unfollow', help="Max Number of People to Unfollow")` to parser.add_argument('-mu', '--max', help="Max Number of People to Unfollow")
> 
> and mnof = `args.max_followers` to `mnof = args.max`
> 
> The argument `max_followers` had not been defined in the parser. Also, I changed `max-unfollow` to `max since the special character `-` was breaking that line.

This is incorrect and not how the argument parser works. The argument parser is working as intended.

Also, has nothing to do with the issue.

**Comment by Correia-jpv** [comment] 2022-09-09 16:01
Duplicate of #3

**Closed as completed by Correia-jpv** 2022-09-09 16:01 UTC
Labels: bug

**Comment by david-kariuki** [comment] 2022-09-10 19:21
Yes, you are right. I noticed it clears the error then just counts and does not unfollow

**Comment by david-kariuki** [comment] 2022-09-10 19:22
Just a question, I noticed you are referring to `args.max_followers` in the unfollow python file. Did you declare it in your arguments

**Comment by Correia-jpv** [comment] 2022-09-10 22:08
> Just a question, I noticed you are referring to `args.max_followers` in the unfollow python file. Did you declare it in your arguments

From [argparse documentation](https://docs.python.org/dev/library/argparse.html#dest):

> For optional argument actions, the value of dest is normally inferred from the option strings. [ArgumentParser](https://docs.python.org/dev/library/argparse.html#argparse.ArgumentParser) generates the value of dest by taking the first long option string and stripping away the initial -- string. If no long option strings were supplied, dest will be derived from the first short option string by stripping the initial - character. Any internal - characters will be converted to _ characters to make sure the string is a valid attribute name.

Dash characters from arguments are converted to underscores.
In this case, the max followers argument is declared as `max-followers` and referred to as `max_followers`

**Comment by david-kariuki** [comment] 2022-09-11 09:23
Thank you. I had outdated code. The code I have did not have all the arguments I am seeing now

**Comment by david-kariuki** [comment] 2022-09-11 09:23
Thank you for the clarification
